---
- name: AAP Hello World Demo
  hosts: all
  gather_facts: false

  tasks:
    - name: Display welcome message
      debug:
        msg: "Welcome Chidananda Reddy ----  GitHub and Ansible Automation Platform!"
